package constants

const TestDataTableName = "DB2WML.HOME_SALES_PREDICT"

const SPLIT_DATA_SQL = "CALL IDAX.SPLIT_DATA('intable=DB2WML.HOME_SALES_VIEW, " +
	"traintable=DB2WML.HOME_SALES_TRAIN, " +
	"testtable=DB2WML.HOME_SALES_PREDICT, " +
	"id=ID, " +
	"fraction=0.95') "

const DROP_MODEL = "call IDAX.DROP_MODEL('model=DB2WML.HOME_SALES_MODEL')"

const LINEAR_REGRESSION_SQL = "CALL IDAX.LINEAR_REGRESSION " +
	" ('model=DB2WML.HOME_SALES_MODEL, " +
	"intable=DB2WML.HOME_SALES_TRAIN, " +
	"id=ID, " +
	"target=SALEPRICE, " +
	"incolumn=LOTAREA;BLDGTYPE;HOUSESTYLE;OVERALLCOND;YEARBUILT;ROOFSTYLE;EXTERCOND;FOUNDATION;BSMTCOND;HEATING;HEATINGQC;CENTRALAIR;ELECTRICAL;FULLBATH;HALFBATH;BEDROOMABVGR;KITCHENABVGR;KITCHENQUAL;TOTRMSABVGRD;FIREPLACES;FIREPLACEQU;GARAGETYPE;GARAGEFINISH;GARAGECARS;GARAGECOND;POOLAREA;POOLQC;FENCE;MOSOLD;YRSOLD, " +
	"coldefrole=ignore, calculatediagnostics=false')"

const PREDICT_LR_SQL = "CALL IDAX.PREDICT_LINEAR_REGRESSION " +
	"('model=DB2WML.HOME_SALES_MODEL, " +
	"intable=DB2WML.HOME_SALES_PREDICT, " +
	"outtable=DB2WML.HOME_SALES_RESULT, " +
	"id=ID')"

var INSERT_SQL = "INSERT INTO " + TestDataTableName +
	"(ID,LOTAREA,BLDGTYPE,HOUSESTYLE,OVERALLCOND,YEARBUILT,ROOFSTYLE,EXTERCOND,FOUNDATION,BSMTCOND,HEATING,HEATINGQC,CENTRALAIR,ELECTRICAL,FULLBATH,HALFBATH,BEDROOMABVGR,KITCHENABVGR,KITCHENQUAL,TOTRMSABVGRD,FIREPLACES,FIREPLACEQU,GARAGETYPE,GARAGEFINISH,GARAGECARS,GARAGECOND,POOLAREA,POOLQC,FENCE,MOSOLD,YRSOLD) " +
	"VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"

const DropOutputTable = "DROP TABLE DB2WML.HOME_SALES_RESULT"

const TABLE_IF_EXISTS = "select tabname from syscat.tables where tabschema='DB2WML' and tabname='HOME_SALES_RESULT'"
const MAXID = "select MAX(ID) + 1 as maxId from " + TestDataTableName

const PREDICTION_RESULT = "SELECT IN.ID AS \"Id\",LOTAREA AS \"LotArea\",BLDGTYPE AS \"BldgType\",HOUSESTYLE AS \"HouseStyle\",OVERALLCOND AS \"OverallCond\",YEARBUILT AS \"YearBuilt\",ROOFSTYLE AS \"RoofStyle\",EXTERCOND AS \"ExterCond\",FOUNDATION AS \"Foundation\",BSMTCOND AS \"BsmtCond\",HEATING AS \"Heating\",HEATINGQC AS \"HeatingQC\",CENTRALAIR AS \"CentralAir\",ELECTRICAL AS \"Electrical\",FULLBATH AS \"FullBath\",HALFBATH AS \"HalfBath\",BEDROOMABVGR AS \"BedroomAbvGr\",KITCHENABVGR AS \"KitchenAbvGr\",KITCHENQUAL AS \"KitchenQual\",TOTRMSABVGRD AS \"TotRmsAbvGrd\",FIREPLACES AS \"Fireplaces\",FIREPLACEQU AS \"FireplaceQu\",GARAGETYPE AS \"GarageType\",GARAGEFINISH AS \"GarageFinish\",GARAGECARS AS \"GarageCars\",GARAGECOND AS \"GarageCond\",POOLAREA AS \"PoolArea\",POOLQC AS \"PoolQC\",FENCE AS \"Fence\",MOSOLD AS \"MoSold\",YRSOLD AS \"YrSold\",OUT.SALEPRICE AS \"SalePrice\" FROM DB2WML.HOME_SALES_PREDICT AS IN , DB2WML.HOME_SALES_RESULT AS OUT WHERE IN.ID=OUT.ID AND OUT.ID=?"
